import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { useState } from "react";
import { Brand, Mandala } from "@/components/brand";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";

export const Route = createFileRoute("/auth")({ head:()=>({meta:[{title:"Sign in — Moments by Studio Click.ed"},{name:"description",content:"Secure access for Studio Click.ed and wedding couples."},{property:"og:title",content:"Sign in — Moments"},{property:"og:description",content:"Securely access your wedding workspace."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}), component: AuthPage });
function AuthPage(){
 const navigate=useNavigate(); const [mode,setMode]=useState<"signin"|"signup">("signin"); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const f=new FormData(e.currentTarget);const email=String(f.get("email"));const password=String(f.get("password"));const result=mode==="signin"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setBusy(false);if(result.error){setMessage(result.error.message);return;}if(mode==="signup"&&!result.data.session){setMessage("Check your email to confirm your account.");return;}await navigate({to:"/dashboard"});}
 async function google(){const result=await lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin});if(result.error)setMessage(result.error.message);}
 return <main className="grid min-h-screen bg-primary text-primary-foreground lg:grid-cols-2"><section className="relative hidden overflow-hidden border-r border-primary-foreground/10 p-12 lg:flex lg:flex-col lg:justify-between"><Mandala className="absolute -right-28 top-1/2 w-[34rem] -translate-y-1/2 text-gold opacity-20"/><Brand light/><div className="relative"><p className="eyebrow">Your celebration at a glance</p><h1 className="mt-5 max-w-lg font-display text-6xl">Every cherished reply, in one beautiful place.</h1></div><p className="relative text-xs text-primary-foreground/40">Private. Personal. Thoughtfully managed.</p></section><section className="flex min-h-screen items-center justify-center bg-background p-5 text-foreground"><div className="w-full max-w-sm"><a href="/" className="mb-12 inline-flex items-center gap-2 text-xs text-muted-foreground"><ArrowLeft className="size-4"/> Back to Moments</a><p className="eyebrow">Private access</p><h2 className="mt-3 font-display text-4xl">{mode==="signin"?"Welcome back":"Create your account"}</h2><p className="mt-3 text-sm text-muted-foreground">For Studio Click.ed and invited couples.</p><form onSubmit={submit} className="mt-9 space-y-6"><label className="block text-xs uppercase tracking-[.12em]">Email<input name="email" required type="email" className="field" placeholder="you@example.com"/></label><label className="block text-xs uppercase tracking-[.12em]">Password<input name="password" required type="password" minLength={6} className="field" placeholder="••••••••"/></label>{message&&<p className="text-sm text-muted-foreground">{message}</p>}<Button className="w-full" size="xl" disabled={busy}>{busy?"Please wait…":mode==="signin"?"Sign in":"Create account"}<ArrowRight/></Button></form><div className="my-6 flex items-center gap-3 text-[10px] uppercase tracking-[.14em] text-muted-foreground"><span className="h-px flex-1 bg-border"/>or<span className="h-px flex-1 bg-border"/></div><Button variant="outline" size="xl" className="w-full" onClick={google}>Continue with Google</Button><button onClick={()=>setMode(mode==="signin"?"signup":"signin")} className="mt-7 w-full text-center text-xs text-muted-foreground underline underline-offset-4">{mode==="signin"?"Need an account? Request access":"Already have access? Sign in"}</button></div></section></main>
}