import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, MoreHorizontal } from "lucide-react";
import { useState } from "react";
import { DashboardShell, Metric } from "@/components/dashboard-shell";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { demoEvents } from "@/lib/moments-data";

export const Route=createFileRoute("/_authenticated/dashboard")({head:()=>({meta:[{title:"Events — Moments Workspace"},{name:"description",content:"Manage wedding events, invitations and RSVP totals."},{property:"og:title",content:"Moments Event Workspace"},{property:"og:description",content:"Wedding invitation and RSVP management."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Dashboard});
function Dashboard(){const [events,setEvents]=useState(demoEvents); const active=events.filter(e=>e.status==="active").length; return <DashboardShell eyebrow="Studio workspace" title="Celebrations"><div className="grid gap-4 sm:grid-cols-3"><Metric label="Live events" value={String(active)} note="Currently receiving replies"/><Metric label="Total invitations" value="518" note="Across all celebrations" icon="users"/><Metric label="Confirmed heads" value="124" note="67% response rate"/></div><section className="mt-10"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-display text-2xl">All events</h2><p className="mt-1 text-xs text-muted-foreground">A considered view of every celebration.</p></div><Button size="sm">New event</Button></div><div className="grid gap-4 xl:grid-cols-3">{events.map(event=><article key={event.id} className="border border-border bg-background p-5"><div className="flex justify-between"><span className={`text-[10px] uppercase tracking-[.16em] ${event.status==="active"?"text-gold":"text-muted-foreground"}`}>{event.status}</span><MoreHorizontal className="size-4 text-muted-foreground"/></div><h3 className="mt-5 font-display text-2xl">{event.title.replace("The Wedding of ","")}</h3><p className="mt-2 text-xs text-muted-foreground">{event.date}</p><div className="my-6 grid grid-cols-2 border-y border-border py-4"><div><strong className="font-display text-2xl font-normal">{event.invites}</strong><span className="block text-[10px] uppercase text-muted-foreground">Invites</span></div><div className="border-l border-border pl-4"><strong className="font-display text-2xl font-normal">{event.confirmed}</strong><span className="block text-[10px] uppercase text-muted-foreground">Confirmed</span></div></div>{event.status==="onboarding"?<label className="flex items-center justify-between text-xs"><span>Agreement signed</span><Switch onCheckedChange={checked=>checked&&setEvents(old=>old.map(e=>e.id===event.id?{...e,status:"active"}:e))}/></label>:event.id===demoEvents[0].id?<Link to="/dashboard/events/$id" params={{id:event.id}} className="flex items-center justify-between text-xs font-semibold uppercase tracking-[.12em]">Manage event <ArrowUpRight className="size-4"/></Link>:<span className="text-xs text-muted-foreground">Awaiting next step</span>}</article>)}</div></section></DashboardShell>}